// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jhFoQ0IQz6SBhjqJNf9IHhDQ12qepN4',
    appId: '1:230523064998:web:afcc0d14473b777355da67',
    messagingSenderId: '230523064998',
    projectId: 'hocgiagacon',
    authDomain: 'hocgiagacon.firebaseapp.com',
    storageBucket: 'hocgiagacon.appspot.com',
    measurementId: 'G-94J1FN3614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXOJwNtna3EKFtDSFEBYasVBhaPri0oo',
    appId: '1:230523064998:android:3dc7d4c6eb4cce5a55da67',
    messagingSenderId: '230523064998',
    projectId: 'hocgiagacon',
    storageBucket: 'hocgiagacon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyLGsqx4VXW-9bbEdIAtG0tn_UalMkec',
    appId: '1:230523064998:ios:6c4d3814520a9c5355da67',
    messagingSenderId: '230523064998',
    projectId: 'hocgiagacon',
    storageBucket: 'hocgiagacon.appspot.com',
    iosBundleId: 'com.example.chickenCombat.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyLGsqx4VXW-9bbEdIAtG0tn_UalMkec',
    appId: '1:230523064998:ios:b7e1153991d0388455da67',
    messagingSenderId: '230523064998',
    projectId: 'hocgiagacon',
    storageBucket: 'hocgiagacon.appspot.com',
    iosBundleId: 'com.example.chickenCombat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jhFoQ0IQz6SBhjqJNf9IHhDQ12qepN4',
    appId: '1:230523064998:web:90b4afe0872aa4f955da67',
    messagingSenderId: '230523064998',
    projectId: 'hocgiagacon',
    authDomain: 'hocgiagacon.firebaseapp.com',
    storageBucket: 'hocgiagacon.appspot.com',
    measurementId: 'G-KBJBKLB74T',
  );
}
