// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYiAMKLq0trj3i3WJ3POs9PYpHbG34Ec',
    appId: '1:662203684781:web:0f65c5e2d19f0a2d387324',
    messagingSenderId: '662203684781',
    projectId: 'chickenleaningai',
    authDomain: 'chickenleaningai.firebaseapp.com',
    storageBucket: 'chickenleaningai.appspot.com',
    measurementId: 'G-NHQPLFNPBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpY92gnRfh9e9v11mon0W_SGOVXsH58A',
    appId: '1:662203684781:android:9d3b7394e72bb4fc387324',
    messagingSenderId: '662203684781',
    projectId: 'chickenleaningai',
    storageBucket: 'chickenleaningai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkY1eamy8DJnoM6sEzo_dypCzF7tog2yU',
    appId: '1:662203684781:ios:35b54f20e3acdc2c387324',
    messagingSenderId: '662203684781',
    projectId: 'chickenleaningai',
    storageBucket: 'chickenleaningai.appspot.com',
    iosBundleId: 'checkenFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkY1eamy8DJnoM6sEzo_dypCzF7tog2yU',
    appId: '1:662203684781:ios:d12aa3795314158a387324',
    messagingSenderId: '662203684781',
    projectId: 'chickenleaningai',
    storageBucket: 'chickenleaningai.appspot.com',
    iosBundleId: 'com.example.chickenCombat.RunnerTests',
  );
}
